name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Check formatting
        run: black --check .
      - name: Run flake8
        run: flake8
      - name: Run tests
        run: pytest
      - name: Build wheel and sdist
        run: python -m build
      - name: Check package
        run: twine check --strict dist/*
      - name: Build standalone binary
        run: ./scripts/package.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smtp-burst-artifacts
          path: dist/
